### ISSUE TITLE
是否可以适配一下官方的fly主题

### ISSUE THREAD

**Issue by hxhc** [tangkaichuan/gridea-search#11]
你好，非常感谢您的搜索功能。我有看到您给一些gridea主题做了适配，也给出了详细的说明。
非常不好意思做一个伸手党，只是我个人之前很少接触网页开发，对html、css和js一窍不通，因此虽然我很想把这个搜索功能加到官方的fly主题里，但心有余而力不足。

如果直接把example下的两个文件夹扔到fly主题里，出来的页面是这样的，与原先的主题有较大出入
![after](https://i.loli.net/2021/01/29/vSkMm6WfDVTbgP9.png)

如果您有时间和精力，是否可以适配一下fly主题，类似这个样子
![before](https://i.loli.net/2021/01/29/9orkHyvlcexpUMR.png)

**Comment by hxhc** [comment]
非常感谢！

**Comment by kytrun** [comment]
搜索功能已加，https://github.com/tangkaichuan/gridea-theme-fly
欢迎尝鲜，提 bug 😛

**Comment by hxhc** [comment]
> 搜索功能已加，https://github.com/tangkaichuan/gridea-theme-fly
> 欢迎尝鲜，提 bug 😛

感谢，已用上主题，目前完美

**Comment by potatoler** [comment]
> 搜索功能已加，https://github.com/tangkaichuan/gridea-theme-fly
> 欢迎尝鲜，提 bug 😛

非常感谢，效果很好
