### ISSUE TITLE
美观问题

### ISSUE THREAD

**Issue by supercatreal** [tangkaichuan/gridea-search#2]
不能够很好的融入主题，建议改成椭圆形（小米电池那个形）搜索框在里面放上放大镜这样就能很好的融入主题了。还有就是搜索出来的结果展示很难看，希望可以再这一方面进行优化。这是个不错的项目，弥补了gridea的不能搜索的不足。

**Comment by tangkaichuan** [comment]
本项目提供的仅仅是本质的搜索功能，你所描述的只是示例，这些都是由主题开发者定制的。

参考：<https://blog.itjoker.cn/>，<http://tangkaichuan.cn/>，<https://i.immmmm.com/>，<https://chiperman.github.io/>
