### ISSUE TITLE
JS Error

### ISSUE THREAD

**Issue by smallfangqwq** [tangkaichuan/gridea-search#4]
在查询时js报错了：报错信息如下gridea-search.js:131 
Uncaught TypeError: Cannot read property 'getElementsByClassName' of null
    at o (VM151 gridea-search.min.js:7)
    at VM151 gridea-search.min.js:7
    at c (VM151 gridea-search.min.js:7)
    at window.onload (VM151 gridea-search.min.js:7)

求解决方案。现无法正常搜索

**Comment by kytrun** [comment]
[这一个标签和 class](https://github.com/tangkaichuan/gridea-search/blob/master/example/templates/search.ejs#L20) 必须保留，我在 README 里说明一下。
