### ISSUE TITLE
一直搜索中怎么办

### ISSUE THREAD

**Issue by ghost** [tangkaichuan/gridea-search#5]
![image](https://user-images.githubusercontent.com/62826113/82221097-0d01c380-990f-11ea-90ed-3560dbd33503.png)

**Comment by kytrun** [comment]
目前搜索结果页也需要包含搜索框。

**Comment by radiumtall** [comment]
怎么包含捏

**Comment by kytrun** [comment]
```html
<form id="gridea-search-form" action="<%= themeConfig.domain %>/search/">
    <input name="q" />
</form>
```

作为公用模板。

**Comment by radiumtall** [comment]
> ```
> <form id="gridea-search-form" action="<%= themeConfig.domain %>/search/">
>     <input name="q" />
> </form>
> ```
> 
> 作为公用模板。


直接下的模板 https://github.com/ITJoker233/Gridea-theme-Chic 里需要改的文件是哪几个呀 不太清楚-.-

**Comment by kytrun** [comment]
这个主题使用的早期版本的搜索功能，开发者没更新，已经不兼容了。建议换其他的主题使用😂

**Comment by radiumtall** [comment]
> 这个主题使用的早期版本的搜索功能，开发者没更新，已经不兼容了。建议换其他的主题使用😂

可惜，感觉害挺好看
